services:
  - type: web
    name: phonebook-backend
    runtime: node
    repo: https://example.com/your-repo-url.git
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

